--[[                                                                           ]]--
--[[  Generated by FAF Map Editor                                              ]]--
--[[                                                                           ]]--
--[[                                                                           ]]--
--[[  Scenario                                                                 ]]--
--[[                                                                           ]]--
Scenario = {
    next_area_id = '0',
    --[[                                                                           ]]--
    --[[  Props                                                                    ]]--
    --[[                                                                           ]]--
    Props = {
    },
    --[[                                                                           ]]--
    --[[  Areas                                                                    ]]--
    --[[                                                                           ]]--
    Areas = {
        ['M3'] = {
            ['rectangle'] = RECTANGLE( 0, 0, 1024, 1024 ),
        },
        ['M2'] = {
            ['rectangle'] = RECTANGLE( 0, 0, 1024, 660 ),
        },
        ['M1'] = {
            ['rectangle'] = RECTANGLE( 0, 90, 450, 600 ),
        },
    },
    --[[                                                                           ]]--
    --[[  Markers                                                                  ]]--
    --[[                                                                           ]]--
    MasterChain = {
        ['_MASTERCHAIN_'] = {
            Markers = {
                ['Player2'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 145.5, 66.18373, 268.5 ),
                },
                ['UEF'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 408.5, 66.4025, 522.5 ),
                },
                ['Player4'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 137.5, 66.45328, 247.5 ),
                },
                ['Player1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 155.5, 66.2267, 259.5 ),
                },
                ['Player5'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 134.5, 66.27358, 264.5 ),
                },
                ['Cybran'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 883.5, 68.76591, 128.5 ),
                },
                ['Unknown'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 947.5, 63.65623, 924.5001 ),
                },
                ['Player3'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 152.5, 66.4025, 244.5 ),
                },
                ['Aeon'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 923.5, 42.58073, 615.5 ),
                },
            },
        },
    },
    Chains = {
    },
    next_queue_id = '0',
    --[[                                                                           ]]--
    --[[  Orders                                                                   ]]--
    --[[                                                                           ]]--
    Orders = {
    },
    next_platoon_id = '0',
    --[[                                                                           ]]--
    --[[  Platoons                                                                 ]]--
    --[[                                                                           ]]--
    Platoons = {
    },
    next_army_id = '0',
    next_group_id = '0',
    next_unit_id = '0',
    --[[                                                                           ]]--
    --[[  Armies                                                                   ]]--
    --[[                                                                           ]]--
    Armies = {
        --[[                                                                           ]]--
        --[[  Player1                                                                  ]]--
        --[[                                                                           ]]--
        ['Player1'] = 
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['Player5'] = 'Ally',
                ['Player3'] = 'Ally',
                ['Player2'] = 'Ally',
                ['Unknown'] = 'Enemy',
                ['UEF'] = 'Enemy',
                ['Player4'] = 'Ally',
                ['Cybran'] = 'Enemy',
                ['Aeon'] = 'Enemy',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['Cybran1'] = {
                        type = 'url0001',
                        orders = '',
                        platoon = '',
                        Position = { 155.5, 66.21107, 259.5 },
                        Orientation = { 0, 0, 0 },
                    },
                    ['Aeon1'] = {
                        type = 'ual0001',
                        orders = '',
                        platoon = '',
                        Position = { 155.5, 66.21107, 259.5 },
                        Orientation = { 0, 0, 0 },
                    },
                    ['UEF1'] = {
                        type = 'uel0001',
                        orders = '',
                        platoon = '',
                        Position = { 155.5, 66.21107, 259.5 },
                        Orientation = { 0, 0, 0 },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  UEF                                                                      ]]--
        --[[                                                                           ]]--
        ['UEF'] = 
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['Player1'] = 'Enemy',
                ['Player5'] = 'Enemy',
                ['Player2'] = 'Enemy',
                ['Unknown'] = 'Ally',
                ['Cybran'] = 'Ally',
                ['Player4'] = 'Enemy',
                ['Player3'] = 'Enemy',
                ['Aeon'] = 'Ally',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['M1_NE_Base'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['M1_NE_Base_D3'] = GROUP {
                                orders = '',
                                platoon = '',
                                Units = {
                                    ['M1_NE_Base_D2'] = GROUP {
                                        orders = '',
                                        platoon = '',
                                        Units = {
                                            ['M1_NE_Base_D1'] = GROUP {
                                                orders = '',
                                                platoon = '',
                                                Units = {
                                                    ['UNIT_0'] = {
                                                        type = 'zeb9501',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 413.5, 66.11732, 176.5 },
                                                        Orientation = { 0, 0, 0 },
                                                    },
                                                    ['UNIT_1'] = {
                                                        type = 'zeb9501',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 413.5, 66.23061, 166.5 },
                                                        Orientation = { 0, 0, 0 },
                                                    },
                                                    ['UNIT_2'] = {
                                                        type = 'zeb9501',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 423.5, 66.17201, 166.5 },
                                                        Orientation = { 0, 0, 0 },
                                                    },
                                                    ['UNIT_3'] = {
                                                        type = 'zeb9501',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 423.5, 66.13685, 176.5 },
                                                        Orientation = { 0, 0, 0 },
                                                    },
                                                    ['UNIT_4'] = {
                                                        type = 'ueb1104',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 410.5, 66.1681, 171.5 },
                                                        Orientation = { 0, 0, 0 },
                                                    },
                                                    ['UNIT_5'] = {
                                                        type = 'ueb1104',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 418.5, 66.11341, 179.5 },
                                                        Orientation = { 0, 0, 0 },
                                                    },
                                                    ['UNIT_6'] = {
                                                        type = 'ueb1104',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 418.5, 66.23451, 163.5 },
                                                        Orientation = { 0, 0, 0 },
                                                    },
                                                    ['UNIT_7'] = {
                                                        type = 'ueb1104',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 426.5, 66.14075, 171.5 },
                                                        Orientation = { 0, 0, 0 },
                                                    },
                                                    ['UNIT_8'] = {
                                                        type = 'ueb1101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 418.5, 66.03529, 177.5 },
                                                        Orientation = { 0, 0, 0 },
                                                    },
                                                    ['UNIT_9'] = {
                                                        type = 'ueb1101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 424.5, 66.14466, 171.5 },
                                                        Orientation = { 0, 0, 0 },
                                                    },
                                                    ['UNIT_10'] = {
                                                        type = 'ueb1101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 418.5, 66.21107, 165.5 },
                                                        Orientation = { 0, 0, 0 },
                                                    },
                                                    ['UNIT_11'] = {
                                                        type = 'ueb1101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 412.5, 66.16029, 171.5 },
                                                        Orientation = { 0, 0, 0 },
                                                    },
                                                    ['UNIT_20'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 428.5, 66.11341, 178.5 },
                                                        Orientation = { 0, 0, 0 },
                                                    },
                                                    ['UNIT_19'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 428.5, 66.11341, 179.5 },
                                                        Orientation = { 0, 0, 0 },
                                                    },
                                                    ['UNIT_18'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 428.5, 66.11341, 180.5 },
                                                        Orientation = { 0, 0, 0 },
                                                    },
                                                    ['UNIT_17'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 428.5, 66.11341, 181.5 },
                                                        Orientation = { 0, 0, 0 },
                                                    },
                                                    ['UNIT_16'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 427.5, 66.11732, 181.5 },
                                                        Orientation = { 0, 0, 0 },
                                                    },
                                                    ['UNIT_21'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 425.5, 66.21498, 161.5 },
                                                        Orientation = { 0, -4.712389, 0 },
                                                    },
                                                    ['UNIT_14'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 425.5, 66.12122, 181.5 },
                                                        Orientation = { 0, 0, 0 },
                                                    },
                                                    ['UNIT_13'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 426.5, 66.12122, 181.5 },
                                                        Orientation = { 0, 0, 0 },
                                                    },
                                                    ['UNIT_12'] = {
                                                        type = 'ueb2104',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 418.5, 66.15638, 171.5 },
                                                        Orientation = { 0, 0, 0 },
                                                    },
                                                    ['UNIT_15'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 426.5, 66.21107, 161.5 },
                                                        Orientation = { 0, -4.712389, 0 },
                                                    },
                                                    ['UNIT_22'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 427.5, 66.21107, 161.5 },
                                                        Orientation = { 0, -4.712389, 0 },
                                                    },
                                                    ['UNIT_23'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 428.5, 66.20716, 161.5 },
                                                        Orientation = { 0, -4.712389, 0 },
                                                    },
                                                    ['UNIT_24'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 428.5, 66.19935, 162.5 },
                                                        Orientation = { 0, -4.712389, 0 },
                                                    },
                                                    ['UNIT_25'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 428.5, 66.17982, 164.5 },
                                                        Orientation = { 0, -4.712389, 0 },
                                                    },
                                                    ['UNIT_26'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 428.5, 66.18764, 163.5 },
                                                        Orientation = { 0, -4.712389, 0 },
                                                    },
                                                    ['UNIT_27'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 408.5, 66.26967, 164.5 },
                                                        Orientation = { 0, -3.141593, 0 },
                                                    },
                                                    ['UNIT_28'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 408.5, 66.29701, 162.5 },
                                                        Orientation = { 0, -3.141593, 0 },
                                                    },
                                                    ['UNIT_29'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 408.5, 66.28139, 163.5 },
                                                        Orientation = { 0, -3.141593, 0 },
                                                    },
                                                    ['UNIT_30'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 408.5, 66.30482, 161.5 },
                                                        Orientation = { 0, -3.141593, 0 },
                                                    },
                                                    ['UNIT_31'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 409.5, 66.30093, 161.5 },
                                                        Orientation = { 0, -3.141593, 0 },
                                                    },
                                                    ['UNIT_32'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 411.5, 66.29701, 161.5 },
                                                        Orientation = { 0, -3.141593, 0 },
                                                    },
                                                    ['UNIT_33'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 410.5, 66.29701, 161.5 },
                                                        Orientation = { 0, -3.141593, 0 },
                                                    },
                                                    ['UNIT_40'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 408.5, 66.1681, 179.5 },
                                                        Orientation = { 0, -1.570796, 0 },
                                                    },
                                                    ['UNIT_39'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 408.5, 66.16419, 178.5 },
                                                        Orientation = { 0, -1.570796, 0 },
                                                    },
                                                    ['UNIT_38'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 408.5, 66.17591, 180.5 },
                                                        Orientation = { 0, -1.570796, 0 },
                                                    },
                                                    ['UNIT_37'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 408.5, 66.17982, 181.5 },
                                                        Orientation = { 0, -1.570796, 0 },
                                                    },
                                                    ['UNIT_36'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 409.5, 66.17201, 181.5 },
                                                        Orientation = { 0, -1.570796, 0 },
                                                    },
                                                    ['UNIT_35'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 411.5, 66.16419, 181.5 },
                                                        Orientation = { 0, -1.570796, 0 },
                                                    },
                                                    ['UNIT_34'] = {
                                                        type = 'ueb5101',
                                                        orders = '',
                                                        platoon = '',
                                                        Position = { 410.5, 66.1681, 181.5 },
                                                        Orientation = { 0, -1.570796, 0 },
                                                    },
                                                },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Cybran                                                                   ]]--
        --[[                                                                           ]]--
        ['Cybran'] = 
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['Player1'] = 'Enemy',
                ['Player5'] = 'Enemy',
                ['Player2'] = 'Enemy',
                ['Player3'] = 'Enemy',
                ['UEF'] = 'Ally',
                ['Player4'] = 'Enemy',
                ['Unknown'] = 'Ally',
                ['Aeon'] = 'Ally',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Aeon                                                                     ]]--
        --[[                                                                           ]]--
        ['Aeon'] = 
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['Player1'] = 'Enemy',
                ['Unknown'] = 'Ally',
                ['Player2'] = 'Enemy',
                ['Player3'] = 'Enemy',
                ['UEF'] = 'Ally',
                ['Player4'] = 'Enemy',
                ['Cybran'] = 'Ally',
                ['Player5'] = 'Enemy',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Unknown                                                                  ]]--
        --[[                                                                           ]]--
        ['Unknown'] = 
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['MindControllers'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['M1_MindController'] = {
                                type = 'xrc1101',
                                orders = '',
                                platoon = '',
                                Position = { 191.5, 66.43765, 566.5 },
                                Orientation = { 0, -4.712389, 0 },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Player2                                                                  ]]--
        --[[                                                                           ]]--
        ['Player2'] = 
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['Player1'] = 'Ally',
                ['Player5'] = 'Ally',
                ['Unknown'] = 'Enemy',
                ['Cybran'] = 'Enemy',
                ['UEF'] = 'Enemy',
                ['Player4'] = 'Ally',
                ['Player3'] = 'Ally',
                ['Aeon'] = 'Enemy',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['UEF2'] = {
                        type = 'uel0001',
                        orders = '',
                        platoon = '',
                        Position = { 145.5, 66.1681, 268.5 },
                        Orientation = { 0, 0, 0 },
                    },
                    ['Aeon2'] = {
                        type = 'ual0001',
                        orders = '',
                        platoon = '',
                        Position = { 145.5, 66.1681, 268.5 },
                        Orientation = { 0, 0, 0 },
                    },
                    ['Cybran2'] = {
                        type = 'url0001',
                        orders = '',
                        platoon = '',
                        Position = { 145.5, 66.1681, 268.5 },
                        Orientation = { 0, 0, 0 },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Player3                                                                  ]]--
        --[[                                                                           ]]--
        ['Player3'] = 
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['Player1'] = 'Ally',
                ['Player5'] = 'Ally',
                ['Player2'] = 'Ally',
                ['Unknown'] = 'Enemy',
                ['UEF'] = 'Enemy',
                ['Player4'] = 'Ally',
                ['Cybran'] = 'Enemy',
                ['Aeon'] = 'Enemy',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['UEF3'] = {
                        type = 'uel0001',
                        orders = '',
                        platoon = '',
                        Position = { 152.5, 66.38686, 244.5 },
                        Orientation = { 0, 0, 0 },
                    },
                    ['Cybran3'] = {
                        type = 'url0001',
                        orders = '',
                        platoon = '',
                        Position = { 152.5, 66.38686, 244.5 },
                        Orientation = { 0, 0, 0 },
                    },
                    ['Aeon3'] = {
                        type = 'ual0001',
                        orders = '',
                        platoon = '',
                        Position = { 152.5, 66.38686, 244.5 },
                        Orientation = { 0, 0, 0 },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Player4                                                                  ]]--
        --[[                                                                           ]]--
        ['Player4'] = 
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['Player1'] = 'Ally',
                ['Player5'] = 'Ally',
                ['Player2'] = 'Ally',
                ['Unknown'] = 'Enemy',
                ['UEF'] = 'Enemy',
                ['Player3'] = 'Ally',
                ['Cybran'] = 'Enemy',
                ['Aeon'] = 'Enemy',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['Cybran4'] = {
                        type = 'url0001',
                        orders = '',
                        platoon = '',
                        Position = { 137.5, 66.43765, 247.5 },
                        Orientation = { 0, 0, 0 },
                    },
                    ['Aeon4'] = {
                        type = 'ual0001',
                        orders = '',
                        platoon = '',
                        Position = { 137.5, 66.43765, 247.5 },
                        Orientation = { 0, 0, 0 },
                    },
                    ['UEF4'] = {
                        type = 'uel0001',
                        orders = '',
                        platoon = '',
                        Position = { 137.5, 66.43765, 247.5 },
                        Orientation = { 0, 0, 0 },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Player5                                                                  ]]--
        --[[                                                                           ]]--
        ['Player5'] = 
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['Player1'] = 'Ally',
                ['Player3'] = 'Ally',
                ['Player2'] = 'Ally',
                ['Unknown'] = 'Enemy',
                ['UEF'] = 'Enemy',
                ['Player4'] = 'Ally',
                ['Cybran'] = 'Enemy',
                ['Aeon'] = 'Enemy',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['Aeon5'] = {
                        type = 'ual0001',
                        orders = '',
                        platoon = '',
                        Position = { 134.5, 66.25795, 264.5 },
                        Orientation = { 0, 0, 0 },
                    },
                    ['Cybran5'] = {
                        type = 'url0001',
                        orders = '',
                        platoon = '',
                        Position = { 134.5, 66.25795, 264.5 },
                        Orientation = { 0, 0, 0 },
                    },
                    ['UEF5'] = {
                        type = 'uel0001',
                        orders = '',
                        platoon = '',
                        Position = { 134.5, 66.25795, 264.5 },
                        Orientation = { 0, 0, 0 },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
    },
}
