--[[                                                                           ]]--
--[[  Generated by FAF Map Editor                                              ]]--
--[[                                                                           ]]--
--[[                                                                           ]]--
--[[  Scenario                                                                 ]]--
--[[                                                                           ]]--
Scenario = {
    next_area_id = '0',
    --[[                                                                           ]]--
    --[[  Props                                                                    ]]--
    --[[                                                                           ]]--
    Props = {
    },
    --[[                                                                           ]]--
    --[[  Areas                                                                    ]]--
    --[[                                                                           ]]--
    Areas = {
        ['M3'] = {
            ['rectangle'] = RECTANGLE( 0, 0, 1024, 1024 ),
        },
        ['M2'] = {
            ['rectangle'] = RECTANGLE( 0, 0, 1024, 700 ),
        },
        ['M1'] = {
            ['rectangle'] = RECTANGLE( 0, 90, 500, 600 ),
        },
    },
    --[[                                                                           ]]--
    --[[  Markers                                                                  ]]--
    --[[                                                                           ]]--
    MasterChain = {
        ['_MASTERCHAIN_'] = {
            Markers = {
                ['Player2'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 145.5, 66.18373, 268.5 ),
                },
                ['UEF'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 408.5, 66.4025, 522.5 ),
                },
                ['Player4'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 137.5, 66.45328, 247.5 ),
                },
                ['Player1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 155.5, 66.2267, 259.5 ),
                },
                ['Unknown'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 947.5, 63.65623, 924.5001 ),
                },
                ['Player5'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 134.5, 66.27358, 264.5 ),
                },
                ['Player3'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 152.5, 66.4025, 244.5 ),
                },
                ['Cybran'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 883.5, 68.76591, 128.5 ),
                },
                ['Aeon'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 923.5, 42.58073, 615.5 ),
                },
            },
        },
    },
    Chains = {
    },
    next_queue_id = '0',
    --[[                                                                           ]]--
    --[[  Orders                                                                   ]]--
    --[[                                                                           ]]--
    Orders = {
    },
    next_platoon_id = '0',
    --[[                                                                           ]]--
    --[[  Platoons                                                                 ]]--
    --[[                                                                           ]]--
    Platoons = {
    },
    next_army_id = '0',
    next_group_id = '0',
    next_unit_id = '0',
    --[[                                                                           ]]--
    --[[  Armies                                                                   ]]--
    --[[                                                                           ]]--
    Armies = {
        --[[                                                                           ]]--
        --[[  Player1                                                                  ]]--
        --[[                                                                           ]]--
        ['Player1'] = 
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['Player5'] = 'Ally',
                ['Player4'] = 'Ally',
                ['Player2'] = 'Ally',
                ['Player3'] = 'Ally',
                ['UEF'] = 'Enemy',
                ['Cybran'] = 'Enemy',
                ['Unknown'] = 'Enemy',
                ['Aeon'] = 'Enemy',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['Cybran1'] = {
                        type = 'url0001',
                        orders = '',
                        platoon = '',
                        Position = { 155.5, 66.21889, 259.5 },
                        Orientation = { 0, 0, 0 },
                    },
                    ['Aeon1'] = {
                        type = 'ual0001',
                        orders = '',
                        platoon = '',
                        Position = { 155.5, 66.21889, 259.5 },
                        Orientation = { 0, 0, 0 },
                    },
                    ['UEF1'] = {
                        type = 'uel0001',
                        orders = '',
                        platoon = '',
                        Position = { 155.5, 66.21889, 259.5 },
                        Orientation = { 0, 0, 0 },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  UEF                                                                      ]]--
        --[[                                                                           ]]--
        ['UEF'] = 
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['Player1'] = 'Enemy',
                ['Player5'] = 'Enemy',
                ['Player2'] = 'Enemy',
                ['Player4'] = 'Enemy',
                ['Player3'] = 'Enemy',
                ['Cybran'] = 'Ally',
                ['Unknown'] = 'Ally',
                ['Aeon'] = 'Ally',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Cybran                                                                   ]]--
        --[[                                                                           ]]--
        ['Cybran'] = 
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['Player1'] = 'Enemy',
                ['Player5'] = 'Enemy',
                ['Player2'] = 'Enemy',
                ['Player4'] = 'Enemy',
                ['UEF'] = 'Ally',
                ['Unknown'] = 'Ally',
                ['Player3'] = 'Enemy',
                ['Aeon'] = 'Ally',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Aeon                                                                     ]]--
        --[[                                                                           ]]--
        ['Aeon'] = 
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['Player1'] = 'Enemy',
                ['Player5'] = 'Enemy',
                ['Player2'] = 'Enemy',
                ['Player4'] = 'Enemy',
                ['UEF'] = 'Ally',
                ['Cybran'] = 'Ally',
                ['Player3'] = 'Enemy',
                ['Unknown'] = 'Ally',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Unknown                                                                  ]]--
        --[[                                                                           ]]--
        ['Unknown'] = 
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Player2                                                                  ]]--
        --[[                                                                           ]]--
        ['Player2'] = 
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['Player1'] = 'Ally',
                ['Player5'] = 'Ally',
                ['Player4'] = 'Ally',
                ['Player3'] = 'Ally',
                ['UEF'] = 'Enemy',
                ['Cybran'] = 'Enemy',
                ['Unknown'] = 'Enemy',
                ['Aeon'] = 'Enemy',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['UEF2'] = {
                        type = 'uel0001',
                        orders = '',
                        platoon = '',
                        Position = { 145.5, 66.17592, 268.5 },
                        Orientation = { 0, 0, 0 },
                    },
                    ['Aeon2'] = {
                        type = 'ual0001',
                        orders = '',
                        platoon = '',
                        Position = { 145.5, 66.17592, 268.5 },
                        Orientation = { 0, 0, 0 },
                    },
                    ['Cybran2'] = {
                        type = 'url0001',
                        orders = '',
                        platoon = '',
                        Position = { 145.5, 66.17592, 268.5 },
                        Orientation = { 0, 0, 0 },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Player3                                                                  ]]--
        --[[                                                                           ]]--
        ['Player3'] = 
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['Player1'] = 'Ally',
                ['Player5'] = 'Ally',
                ['Player2'] = 'Ally',
                ['Player4'] = 'Ally',
                ['UEF'] = 'Enemy',
                ['Cybran'] = 'Enemy',
                ['Unknown'] = 'Enemy',
                ['Aeon'] = 'Enemy',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['UEF3'] = {
                        type = 'uel0001',
                        orders = '',
                        platoon = '',
                        Position = { 152.5, 66.39468, 244.5 },
                        Orientation = { 0, 0, 0 },
                    },
                    ['Cybran3'] = {
                        type = 'url0001',
                        orders = '',
                        platoon = '',
                        Position = { 152.5, 66.39468, 244.5 },
                        Orientation = { 0, 0, 0 },
                    },
                    ['Aeon3'] = {
                        type = 'ual0001',
                        orders = '',
                        platoon = '',
                        Position = { 152.5, 66.39468, 244.5 },
                        Orientation = { 0, 0, 0 },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Player4                                                                  ]]--
        --[[                                                                           ]]--
        ['Player4'] = 
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['Player1'] = 'Ally',
                ['Player5'] = 'Ally',
                ['Player2'] = 'Ally',
                ['Player3'] = 'Ally',
                ['UEF'] = 'Enemy',
                ['Cybran'] = 'Enemy',
                ['Unknown'] = 'Enemy',
                ['Aeon'] = 'Enemy',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['Cybran4'] = {
                        type = 'url0001',
                        orders = '',
                        platoon = '',
                        Position = { 137.5, 66.44546, 247.5 },
                        Orientation = { 0, 0, 0 },
                    },
                    ['Aeon4'] = {
                        type = 'ual0001',
                        orders = '',
                        platoon = '',
                        Position = { 137.5, 66.44546, 247.5 },
                        Orientation = { 0, 0, 0 },
                    },
                    ['UEF4'] = {
                        type = 'uel0001',
                        orders = '',
                        platoon = '',
                        Position = { 137.5, 66.44546, 247.5 },
                        Orientation = { 0, 0, 0 },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Player5                                                                  ]]--
        --[[                                                                           ]]--
        ['Player5'] = 
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['Player1'] = 'Ally',
                ['Player4'] = 'Ally',
                ['Player2'] = 'Ally',
                ['Player3'] = 'Ally',
                ['UEF'] = 'Enemy',
                ['Cybran'] = 'Enemy',
                ['Unknown'] = 'Enemy',
                ['Aeon'] = 'Enemy',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['Aeon5'] = {
                        type = 'ual0001',
                        orders = '',
                        platoon = '',
                        Position = { 134.5, 66.26576, 264.5 },
                        Orientation = { 0, 0, 0 },
                    },
                    ['Cybran5'] = {
                        type = 'url0001',
                        orders = '',
                        platoon = '',
                        Position = { 134.5, 66.26576, 264.5 },
                        Orientation = { 0, 0, 0 },
                    },
                    ['UEF5'] = {
                        type = 'uel0001',
                        orders = '',
                        platoon = '',
                        Position = { 134.5, 66.26576, 264.5 },
                        Orientation = { 0, 0, 0 },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
    },
}
